### ISSUE TITLE
Simple Decode Example Not Working

### ISSUE THREAD

**Issue by aajtodd** [creationix/msgpack-js-browser#10]
I have yet to be able to get msgpack-python and msgpack-js-browser to talk. For the most part decoding of messages seems to go ok from server-client with some quirks. Sending messages to the server using msgpack-js-browser is having problems though.

To go a step further msgpack-js-browser seems to have issues decoding messages that it encoded. Small example:

```javascript
var x = "1af60c36-497c-46cb-8408-78cab2a54a5b"; 
var encoded = msgpack.encode(x);
var decoded = msgpack.decode(encoded);  // ERROR
console.log(decoded);
```

I have seen both "Invalid byte a5" and  "Uncaught RangeError: Offset is outside the bounds of the DataView"

Is there something I'm doing wrong here?

**Comment by creationix** [comment]
Sounds like a regression, @ambrusc are you able to give this a look over?

**Comment by ambrusc** [comment]
Sure, I just got back into the country, but I'll take a look at it today :)

**Comment by creationix** [comment]
@ambrusc this is fixed now right?  I merged your two PRs.

**Comment by ambrusc** [comment]
@creationix, @aajtodd Thanks! The regression should be fixed and has a new unit test.
