### ISSUE TITLE
Can I use this in prod?

### ISSUE THREAD

**Issue by chintan-mishra** [creationix/msgpack-js-browser#15]
At [8hoot](https://8hoot.com), we have all our APIs in MsgPack. This was good as we have a mobile app. However, we are developing a web app and it was hard to find a good MsgPack project to go with. Can you share your perspective on using this in prod web app?

**Comment by creationix** [comment]
This implements an older version of the spec and probably won't be good if any of your other services use the latest version.

**Comment by chintan-mishra** [comment]
Thanks for the clarification. I will keep this in mind.
