### ISSUE TITLE
msgpack 5 update

### ISSUE THREAD

**Issue by alisabri** [creationix/msgpack-js-browser#5]
Hi Tim,
Thanks for sharing this code. I think it is still the one that can be used on client side (in terms of size and speed). I am using it on an online lua repl in combination with lua-MessagePack (spec 5). Long story short, I have updated your msgpack-js-browser according to msgpack 5 spec. (one can send binary strings from server side by lua-MessagePack and receive binary strings without utf-8 conversion, lua-MessagePack is quite flexible by the way). So, if you would like to update your code I can gladly send a pull request.

Regards
Ali

**Comment by tarnic** [comment]
Ali,
As you are the only one I can find that has done this, would you mind publishing your copy of msgpack5-js-browser? I have a project that needs this implementation asap and cannot seem to find it anywhere else.

Thank you
-Zack

**Comment by alisabri** [comment]
Hi Zack,
Sure I can.

**Comment by tarnic** [comment]
Ali,
Thanks for getting back to me so quickly. I actually need this as soon as you can get it to me. My email is me@ZacheryRodgers.com 

Much appreciated,
-Zack

**Comment by aajtodd** [comment]
What is the status of v5 support in the browser?

Thanks!

**Comment by creationix** [comment]
I believe this is v5 now (see #6).  Sorry for not closing this issue when it was updated.

**Comment by aajtodd** [comment]
Yes I saw that and was browsing the code and saw pieces from v5 so I was a bit confused.

Thanks for clearing that up!
